---
title: "Research"
format: html
---


### Causal inference with observational data

I am interested in the formulation, identification, and estimation of stochastic interventions and dynamic treatment regimes using observational data. My work leverages graphical models, partial identification techniques, and transport maps to support more robust and uncertainty-aware decision-making.

Papers:

- Upcoming.


### Graphical models for information selection
My research explores the specification of graphical models to represent selection mechanisms, missing data, and attrition, and the functional shifts they may induce. I have formulated policy-oriented causal queries tailored to these settings and developed graphical criteria to determine when such queries can be recovered from observational data.

Papers:

- **de Aguas**, Henckel, Pensar, Biele (2025). _Causal inference amid missingness-specific independencies and mechanism shifts_. [UAI proceedings (upcoming)](https://arxiv.org/abs/2506.15441).
- **de Aguas**, Pensar, Varnet-Pérez, Biele (2025). _Recovery and inference of causal effects with sequential adjustment for confounding and attrition_. [Journal of Causal Inference](https://www.degruyterbrill.com/document/doi/10.1515/jci-2024-0009/html).

### Semiparametric estimation theory
I have developed semiparametric estimators for causal effects that are both flexible and multiply robust to model misspecification, and that offer stable asymptotic uncertainty quantification. My work has focused on estimators for queries based on sequential regressions and for bounds of partially identified counterfactual parameters.

Papers:

- **de Aguas**, Pensar, Frigessi, Biele (2025). _Representation learning for collaborative targeted estimation of causal effects under attrition_. Upcoming.
- **de Aguas**, Krumscheid, Pensar, Biele (2025). _The probability of tiered benefit: Partial identification with robust and stable inference_. [CLeaR proceedings (upcoming)](https://arxiv.org/abs/2502.10049).

### Spatial econometrics

My research has investigated the identification and estimation of spillover and contagion effects of spatially targeted policies in the presence of network interference. I have focused on agent-based systems with strategic complementarity, aiming to characterize policy effects at the resulting Nash equilibrium.

Master's thesis:

- **de Aguas** (2017). _Network externalities in the management of waste from rural production in the provinces of Colombia: a structural econometric model of a network game with strategic complements_. [Thesis in Spanish] Universidad de los Andes.

### Applications

I have applied the causal, statistical, and machine learning methods I’ve developed to practical tasks such as:

- the evaluation of benefits from pharmacological treatment for ADHD,
- the analysis of international trade and investment flows, 
- the design and evaluation of randomized experiments for mobile banking products, and
- the quantitative assessment of regional competitiveness, among others.


